### ISSUE TITLE
Quarto license not read

### ISSUE THREAD

**Issue by roaldarbol** [continuous-foundation/pubmatter#14]
If you load from a Quarto document, the `license` filed is not being read. 
```yaml
license: CC-BY-4.0
```
resolves to:
```typst
    license: (
      id: "", 
      name: "", 
      url: ""
    )
```

There is a workaround which is to manually specify the `id`, `name` and `url`:
```yaml
license:
   id: CC-BY-4.0
   name: CC-BY-4.0
   url: https://creativecommons.org/licenses/by/4.0/
```
